name: flvtterm
description: Pure Dart VRM and VRMA parsing/runtime core.
version: 0.2.0
repository: https://github.com/ProjectKokage/flvtterm

environment:
  sdk: ^3.11.5

dependencies:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
